name: spell
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=23.3.2
  - python=3.8.18
  - pip:
      - brew-distance==1.0.1
      - certifi==2023.11.17
      - charset-normalizer==3.3.2
      - click==8.1.7
      - idna==3.6
      - joblib==1.3.2
      - levenshtein==0.23.0
      - nltk==3.8.1
      - numpy==1.24.4
      - pandas==2.0.3
      - python-dateutil==2.8.2
      - python-levenshtein==0.23.0
      - pytrec-eval-terrier==0.5.6
      - pytz==2023.3.post1
      - rapidfuzz==3.6.1
      - regex==2023.12.25
      - requests==2.31.0
      - six==1.16.0
      - tqdm==4.66.1
      - tzdata==2023.4
      - urllib3==2.1.0
